In [40]:
from sklearn import preprocessing
import pandas as pd
import numpy as np

inpath = "D:/Disco D/bigData/data/"
df = pd.read_csv(inpath + "base_datos_2008.csv", nrows = 100000)
df = df[["DepDelay", "ArrDelay", "Distance", "AirTime", "Origin"]].dropna()
type(df)
df.head(10)

DepDelay  ArrDelay  Distance  AirTime Origin
0       8.0     -14.0       810    116.0    IAD
1      19.0       2.0       810    113.0    IAD
2       8.0      14.0       515     76.0    IND
3      -4.0      -6.0       515     78.0    IND
4      34.0      34.0       515     77.0    IND
5      25.0      11.0       688     87.0    IND
6      67.0      57.0      1591    230.0    IND
7      -1.0     -18.0      1591    219.0    IND
8       2.0       2.0       451     70.0    IND
9       0.0     -16.0       451     70.0    IND

In [32]:
 ### Para machine learning, susualmente se usan datos escalados
  # Algunas opciones para escalar datos son:

# Normalizar a media 0 y sd 1
x_scaled = preprocessing.scale(df)
type(x_scaled)

numpy.ndarray

In [11]:
x_scaled.mean(axis = 0) # axis = 0 para que haga la operacion en cada columna

array([1.07267490e-17, 2.47651119e-17, 1.19506063e-16, 1.01364179e-16])

In [ ]:
x_scaled.std(axis = 0)

In [30]:
df.iloc[2] # forma de acceder en data frames

DepDelay      8.0
ArrDelay     14.0
Distance    515.0
AirTime      76.0
Name: 2, dtype: float64

In [33]:
x_scaled[2] #forma de acceder a un numpy array

array([-0.08247884,  0.26706167, -0.26709367, -0.29264705])

In [36]:
 # Otra escala que se suele aplicar es la de establecer nuevos maximos y minimos
    
min_max_scaler = preprocessing.MinMaxScaler([1,10])
x_train_minMax = min_max_scaler.fit_transform(df)
x_train_minMax

array([[1.83571429, 1.69479354, 3.84001763, 3.62184874],
       [2.0125    , 1.95332136, 3.84001763, 3.54621849],
       [1.83571429, 2.14721724, 2.66989863, 2.61344538],
       ...,
       [2.86428571, 2.93895871, 4.06214191, 3.44537815],
       [2.04464286, 2.09874327, 4.06214191, 3.26890756],
       [1.75535714, 2.09874327, 4.06214191, 3.31932773]])

In [39]:
 # O con variables dummies
hund = df.head(100)
pd.get_dummies(hund["Origin"])

IAD  IND  ISP  JAN  JAX  LAS
0     1    0    0    0    0    0
1     1    0    0    0    0    0
2     0    1    0    0    0    0
3     0    1    0    0    0    0
4     0    1    0    0    0    0
..  ...  ...  ...  ...  ...  ...
95    0    0    0    0    0    1
96    0    0    0    0    0    1
97    0    0    0    0    0    1
98    0    0    0    0    0    1
99    0    0    0    0    0    1

[100 rows x 6 columns]