In [2]:
import numpy as np
import pandas as pd

In [9]:
arr1 = [0,1,2,3,4,5]  # LISTA
arr1[0] # Python es cero indexado, empieza a contar desde el indice 0

0

In [8]:
arr1[2:4] # Python interpreta el ultimo valor señalado como tope, pero no lo toma en cuenta

[2, 3]

In [ ]:
arr1[:] # imprime todos
arr1[0:]

In [4]:
# NUMPY ARRAYS PARA GRANDES VOLUMENES DE DATOS, OPERACIONES, MUESTREO
## Array dos dimensiones



2

In [13]:
arr1 = np.array([[2,5,6,7,8], [6,4,5,8,9], [6,0,4,8,1]]) 
arr1[0,2]

6

In [20]:
# Array tres dimensiones / Ej, tres clientes valoran 4 productos en dos años distintos
arr2 = np.array([[[3,6,9,0], [4,7,9,2]], [[5,8,2,4], [6,9,3,6]], [[4,7,0,2], [0,4,9,1]]])
arr2[0,0,3]
arr2.shape

(3, 2, 4)

In [112]:
np.zeros((3,2,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [113]:
np.ones((3,2,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [114]:
arr2.mean() #o
np.mean(arr2)

# media aplicado a las dimensiones
arr2.mean(axis =0)
arr2.mean(axis =1)
arr2.mean(axis =2)

array([[4.5 , 5.5 ],
       [4.75, 6.  ],
       [3.25, 3.5 ]])

In [115]:
 ###reshape ordena un vector de acuerdo a una dimensionalidad dada
np.reshape([1,2,3,4,5,6,7,8,9,10,11,12], (3,2,2))



array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [116]:
 ### np.random
    
np.random.rand(10)
np.random.rand(2,2)

array([[0.52286029, 0.1215506 ],
       [0.2669019 , 0.55077062]])

In [117]:
inpath = "D:/Disco D/bigData/data/"
df = pd.read_csv(inpath + "Flights_2008.csv", nrows = 1000000)

In [118]:
 ### Coeficiente de Correlacion

df.dropna(inplace = True, subset = ["ArrDelay", "DepDelay", "DepTime"])


In [119]:
np.corrcoef([df["ArrDelay"], df["DepTime"], df["DepDelay"]])  ## No admite NAs

array([[1.        , 0.17978801, 0.93490112],
       [0.17978801, 1.        , 0.21229661],
       [0.93490112, 0.21229661, 1.        ]])

In [120]:
df.corr() # Tabla de correlaciones, lo ideal es sacar las variables no-numericas 

Year     Month  DayofMonth  DayOfWeek   DepTime  \
Year                NaN       NaN         NaN        NaN       NaN   
Month               NaN  1.000000   -0.015050   0.030930  0.005771   
DayofMonth          NaN -0.015050    1.000000  -0.051893 -0.004149   
DayOfWeek           NaN  0.030930   -0.051893   1.000000  0.006505   
DepTime             NaN  0.005771   -0.004149   0.006505  1.000000   
CRSDepTime          NaN  0.001497   -0.002338   0.010266  0.967093   
ArrTime             NaN -0.007122    0.001970   0.005845  0.718832   
CRSArrTime          NaN -0.009800   -0.000563   0.007485  0.801405   
FlightNum           NaN  0.079810   -0.005089  -0.003372 -0.001497   
ActualElapsedTime   NaN -0.074488    0.009748   0.005525 -0.033971   
CRSElapsedTime      NaN -0.076087    0.005772   0.012497 -0.025449   
AirTime             NaN -0.069707    0.007797   0.009195 -0.031907   
ArrDelay            NaN  0.031751   -0.016971  -0.020013  0.179788   
DepDelay            NaN  0.032285   -0.025893  -0.009137  0.212297   
Distance            NaN -0.070562    0.004336   0.013937 -0.021899   
TaxiIn              NaN -0.039301   -0.013975   0.007376 -0.028305   
TaxiOut             NaN -0.028302    0.020010  -0.023813 -0.007641   
Cancelled           NaN       NaN         NaN        NaN       NaN   
Diverted            NaN       NaN         NaN        NaN       NaN   
CarrierDelay        NaN -0.007918   -0.026833   0.011215  0.013935   
WeatherDelay        NaN  0.023720    0.002860  -0.004178  0.004591   
NASDelay            NaN -0.018685    0.046824  -0.051235 -0.031814   
SecurityDelay       NaN -0.000285   -0.018356   0.008752 -0.008924   
LateAircraftDelay   NaN  0.035021   -0.010162  -0.002767  0.219831   

                   CRSDepTime   ArrTime  CRSArrTime  FlightNum  \
Year                      NaN       NaN         NaN        NaN   
Month                0.001497 -0.007122   -0.009800   0.079810   
DayofMonth          -0.002338  0.001970   -0.000563  -0.005089   
DayOfWeek            0.010266  0.005845    0.007485  -0.003372   
DepTime              0.967093  0.718832    0.801405  -0.001497   
CRSDepTime           1.000000  0.701446    0.800630  -0.013377   
ArrTime              0.701446  1.000000    0.857240  -0.011925   
CRSArrTime           0.800630  0.857240    1.000000  -0.025392   
FlightNum           -0.013377 -0.011925   -0.025392   1.000000   
ActualElapsedTime   -0.031518  0.027351    0.036679  -0.289356   
CRSElapsedTime      -0.020645  0.031429    0.047353  -0.302250   
AirTime             -0.027183  0.026009    0.038180  -0.314668   
ArrDelay             0.102853  0.073489    0.098478   0.068460   
DepDelay             0.132519  0.087577    0.126896   0.053206   
Distance            -0.014220  0.026093    0.044240  -0.333416   
TaxiIn              -0.032370  0.009363   -0.002497   0.023670   
TaxiOut             -0.018797  0.010162    0.000617   0.073521   
Cancelled                 NaN       NaN         NaN        NaN   
Diverted                  NaN       NaN         NaN        NaN   
CarrierDelay        -0.046834 -0.044245   -0.047146   0.094233   
WeatherDelay        -0.022649 -0.018817   -0.018615   0.066190   
NASDelay            -0.074218  0.016260   -0.048304   0.010670   
SecurityDelay       -0.009042 -0.004983   -0.008037  -0.006524   
LateAircraftDelay    0.187314  0.014447    0.161782  -0.021083   

                   ActualElapsedTime  ...  Distance    TaxiIn   TaxiOut  \
Year                             NaN  ...       NaN       NaN       NaN   
Month                      -0.074488  ... -0.070562 -0.039301 -0.028302   
DayofMonth                  0.009748  ...  0.004336 -0.013975  0.020010   
DayOfWeek                   0.005525  ...  0.013937  0.007376 -0.023813   
DepTime                    -0.033971  ... -0.021899 -0.028305 -0.007641   
CRSDepTime                 -0.031518  ... -0.014220 -0.032370 -0.018797   
ArrTime                     0.027351  ...  0.026093  0.009363  0.010162   
CRSArrTime       

In [121]:
df.drop(inplace = True, columns = ["Month", "Year", "Cancelled", "Diverted"])


In [122]:
corr = round(df.corr(), 3)
corr.style.background_gradient()

In [123]:
 ### Test Chi Cuadrado
    # Importante porque permite encontrar relaciones entre variables cualitativas mediante tablas de contingencia
    #1  
    
df = pd.read_csv(inpath + "base_datos_2008.csv")
df

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0        2008      1           3          4   2003.0        1955   2211.0   
1        2008      1           3          4    754.0         735   1002.0   
2        2008      1           3          4    628.0         620    804.0   
3        2008      1           3          4    926.0         930   1054.0   
4        2008      1           3          4   1829.0        1755   1959.0   
...       ...    ...         ...        ...      ...         ...      ...   
7009723  2008     12          13          6   1002.0         959   1204.0   
7009724  2008     12          13          6    834.0         835   1021.0   
7009725  2008     12          13          6    655.0         700    856.0   
7009726  2008     12          13          6   1251.0        1240   1446.0   
7009727  2008     12          13          6   1110.0        1103   1413.0   

         CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
0              2225            WN        335  ...    4.0      8.0          0   
1              1000            WN       3231  ...    5.0     10.0          0   
2               750            WN        448  ...    3.0     17.0          0   
3              1100            WN       1746  ...    3.0      7.0          0   
4              1925            WN       3920  ...    3.0     10.0          0   
...             ...           ...        ...  ...    ...      ...        ...   
7009723        1150            DL       1636  ...    6.0     45.0          0   
7009724        1023            DL       1637  ...    5.0     23.0          0   
7009725         856            DL       1638  ...   24.0     12.0          0   
7009726        1437            DL       1639  ...   13.0     13.0          0   
7009727        1418            DL       1641  ...    8.0     11.0          0   

         CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
0                     NaN         0           NaN          NaN      NaN   
1                     NaN         0           NaN          NaN      NaN   
2                     NaN         0           NaN          NaN      NaN   
3                     NaN         0           NaN          NaN      NaN   
4                     NaN         0           2.0          0.0      0.0   
...                   ...       ...           ...          ...      ...   
7009723               NaN         0           NaN          NaN      NaN   
7009724               NaN         0           NaN          NaN      NaN   
7009725               NaN         0           NaN          NaN      NaN   
7009726               NaN         0           NaN          NaN      NaN   
7009727               NaN         0           NaN          NaN      NaN   

         SecurityDelay  LateAircraftDelay  
0                  NaN                NaN  
1                  NaN                NaN  
2                  NaN                NaN  
3                  NaN                NaN  
4                  0.0               32.0  
...                ...                ...  
7009723            NaN                NaN  
7009724            NaN                NaN  
7009725            NaN                NaN  
7009726            NaN                NaN  
7009727            NaN                NaN  

[7009728 rows x 29 columns]

In [124]:
np.random.seed(0)
df = df[df["Origin"].isin(["HOU", "ATL", "IND"])]
df = df.sample(frac = 1) #ordena a partir del orden de las primeras columnas
df = df[0:100000]  # se selecciona un pequeño grupo porque a mayor escala los patrones tienden a repetirse
df

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
954052   2008      2          23          6   2153.0        2010   2322.0   
4599196  2008      8          12          2    930.0         930   1032.0   
5727901  2008     10          23          4   1304.0        1308   1438.0   
6459675  2008     11          10          1   1102.0        1055   1213.0   
6798519  2008     12          15          1   1542.0        1542   1629.0   
...       ...    ...         ...        ...      ...         ...      ...   
3591573  2008      6           9          1   1607.0        1605   1713.0   
4758969  2008      8           2          6   1126.0        1045   1311.0   
6451827  2008     11           3          1   1911.0        1916   1939.0   
6372124  2008     11           1          6   1116.0        1110   1302.0   
589966   2008      1           2          3   2059.0        2031   2307.0   

         CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
954052         2136            FL        143  ...    6.0     22.0          0   
4599196        1023            FL        540  ...    4.0     17.0          0   
5727901        1442            FL        174  ...    4.0     14.0          0   
6459675        1220            DL        745  ...    5.0     14.0          0   
6798519        1636            FL         35  ...    6.0     11.0          0   
...             ...           ...        ...  ...    ...      ...        ...   
3591573        1719            DL       1743  ...    4.0     17.0          0   
4758969        1235            AA       2035  ...    7.0     17.0          0   
6451827        1932            DL       1723  ...    6.0     39.0          0   
6372124        1310            AA       1039  ...    3.0     17.0          0   
589966         2234            DL       1483  ...   29.0     26.0          0   

         CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
954052                NaN         0           0.0          0.0      3.0   
4599196               NaN         0           NaN          NaN      NaN   
5727901               NaN         0           NaN          NaN      NaN   
6459675               NaN         0           NaN          NaN      NaN   
6798519               NaN         0           NaN          NaN      NaN   
...                   ...       ...           ...          ...      ...   
3591573               NaN         0           NaN          NaN      NaN   
4758969               NaN         0           6.0          0.0      0.0   
6451827               NaN         0           NaN          NaN      NaN   
6372124               NaN         0           NaN          NaN      NaN   
589966                NaN         0          28.0          0.0      5.0   

         SecurityDelay  LateAircraftDelay  
954052             0.0              103.0  
4599196            NaN                NaN  
5727901            NaN                NaN  
6459675            NaN                NaN  
6798519            NaN                NaN  
...                ...                ...  
3591573            NaN                NaN  
4758969            0.0               30.0  
6451827            NaN                NaN  
6372124            NaN                NaN  
589966             0.0                0.0  

[100000 rows x 29 columns]

In [125]:
 # haremos una tabla de frecuencias con la clasificacion booleana a partir de la siguiente condicion
    
df["BigDelay"] = df["ArrDelay"] > 30
observados = pd.crosstab(index = df["BigDelay"], columns = df["Origin"], margins = True) # Tabla de contingencia #margins = los totales
observados

Origin      ATL    HOU   IND     All
BigDelay                            
False     68936   9659  7539   86134
True      11579   1341   946   13866
All       80515  11000  8485  100000

In [126]:
 # Importamos el paquete del test de chi
    
from scipy.stats import chi2_contingency
test = chi2_contingency(observados) # arroja tres resultados a) estadistico, b) p-valor, c) matriz de esperados si no hubiera relacion entre variables
test

(96.17665065462351,
 1.572578363276848e-18,
 6,
 array([[ 69350.7901,   9474.74  ,   7308.4699,  86134.    ],
        [ 11164.2099,   1525.26  ,   1176.5301,  13866.    ],
        [ 80515.    ,  11000.    ,   8485.    , 100000.    ]]))

In [127]:
esperados = pd.DataFrame(test[3])
esperados

0         1          2         3
0  69350.7901   9474.74  7308.4699   86134.0
1  11164.2099   1525.26  1176.5301   13866.0
2  80515.0000  11000.00  8485.0000  100000.0

In [128]:
 # los anteriores valores son aproximaciones teoricas, pero para su mejor intepretacion, se trabajara con los valores relativos
    
esperados_relatv = round(esperados.apply(lambda r:r/len(df) * 100, axis = 1), 2) # lambda porque es funcion sin nombre
esperados_relatv

0      1     2       3
0  69.35   9.47  7.31   86.13
1  11.16   1.53  1.18   13.87
2  80.52  11.00  8.48  100.00

In [129]:
 # lo mismo para la tabla de observados
    
observados_relatv = round(observados.apply(lambda r:r/len(df) * 100, axis = 1), 2) # lambda porque es funcion sin nombre
observados_relatv

Origin      ATL    HOU   IND     All
BigDelay                            
False     68.94   9.66  7.54   86.13
True      11.58   1.34  0.95   13.87
All       80.52  11.00  8.48  100.00

In [130]:
test[1]

1.572578363276848e-18

In [131]:
 # Resumen Test de Chi Squared
    
# Si p-valor < 0.05, hay diferencias significativas, hay relacion entre variables
# Si p-valor > 0.05, no hay diferencias significativas, No habria relacion entre variables

In [132]:
 ### Analisis de Outliers
    
from sklearn.covariance import EllipticEnvelope #para determinar outliers en varias columnas a la vez

outliers = EllipticEnvelope(contamination = 0.01) #selecciona el 1% de los datos mas alejados de la media
var_list = ["DepDelay", "TaxiIn", "TaxiOut", "CarrierDelay", "WeatherDelay", "NASDelay", "SecurityDelay", "LateAircraftDelay"]
x = np.array(df.loc[:,var_list].dropna()) # accede a filas o columnas por etiquetas o booleanos con df.loc
len(x)

24348

In [133]:
# entrenar el modelo Elliptic

outliers.fit(x) # lee arrays unicamente
pred = outliers.predict(x)
elipse_outl = np.where(pred == -1) # nos muestra los indices en donde estan los valores filtrados
elipse_outl

(array([   37,    48,    60,   275,   487,   779,   806,   824,   825,
         1342,  1445,  1471,  1563,  1617,  1658,  1700,  1741,  1759,
         1978,  1988,  2030,  2172,  2395,  2481,  2515,  2850,  2883,
         3162,  3245,  3263,  3354,  3515,  3587,  3599,  3620,  3690,
         3852,  4061,  4069,  4077,  4088,  4128,  4217,  4267,  4333,
         4511,  4716,  4733,  4812,  4915,  4940,  5128,  5165,  5246,
         5390,  5430,  5493,  5600,  5647,  5830,  5844,  5845,  5912,
         6070,  6221,  6248,  6249,  6309,  6325,  6406,  6704,  6840,
         6894,  6949,  6961,  7027,  7058,  7062,  7123,  7389,  7422,
         7485,  7591,  7600,  7746,  7833,  7889,  8024,  8049,  8057,
         8209,  8216,  8328,  8329,  8509,  8530,  9084,  9264,  9356,
         9450,  9578,  9586, 10215, 10278, 10306, 10393, 10442, 10560,
        10562, 10757, 11334, 11344, 11380, 11531, 11546, 11576, 11589,
        11854, 11870, 11957, 12116, 12279, 12329, 12343, 12349, 12383,
      

In [135]:
df.loc[:,var_list]


DepDelay  TaxiIn  TaxiOut  CarrierDelay  WeatherDelay  NASDelay  \
954052      103.0     6.0     22.0           0.0           0.0       3.0   
4599196       0.0     4.0     17.0           NaN           NaN       NaN   
5727901      -4.0     4.0     14.0           NaN           NaN       NaN   
6459675       7.0     5.0     14.0           NaN           NaN       NaN   
6798519       0.0     6.0     11.0           NaN           NaN       NaN   
...           ...     ...      ...           ...           ...       ...   
3591573       2.0     4.0     17.0           NaN           NaN       NaN   
4758969      41.0     7.0     17.0           6.0           0.0       0.0   
6451827      -5.0     6.0     39.0           NaN           NaN       NaN   
6372124       6.0     3.0     17.0           NaN           NaN       NaN   
589966       28.0    29.0     26.0          28.0           0.0       5.0   

         SecurityDelay  LateAircraftDelay  
954052             0.0              103.0  
4599196            NaN                NaN  
5727901            NaN                NaN  
6459675            NaN                NaN  
6798519            NaN                NaN  
...                ...                ...  
3591573            NaN                NaN  
4758969            0.0               30.0  
6451827            NaN                NaN  
6372124            NaN                NaN  
589966             0.0                0.0  

[100000 rows x 8 columns]

In [139]:
x

array([[103.,   6.,  22., ...,   3.,   0., 103.],
       [ 17.,   6.,  17., ...,   0.,   0.,  17.],
       [ 63.,   7.,  19., ...,   0.,   0.,  46.],
       ...,
       [108.,   3.,  16., ...,   0.,   0.,  92.],
       [ 41.,   7.,  17., ...,   0.,   0.,  30.],
       [ 28.,  29.,  26., ...,   5.,   0.,   0.]])